### ISSUE TITLE
Ca marche pas

### ISSUE THREAD

**Issue by dev0banana** [matiasvlevi/Dannjs-FlappyBird#1]
Ca marche pas :/

**Comment by matiasvlevi** [comment]
A little more insight would help? The simulation definitely works. Are the parameters perfectly tuned? maybe not that much. There are 3 or 4 commented out Dann models in the `bird.js` file. You can also play with the mutation rate/function in order to give them different behavior change every generation. Play with the generation value, etc. Genetic simulations are not the kind of thing that doesn't work, they need tuning.
I should have probably specified it in the readme.

I should have also added DOM elements giving the user access to simulation parameters. Wanna do it?
